server:
  port: 8888

logging:
  file:
    path: mylog.log

#logging:
#  path: logs
#  file: mylog.log

spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mtsql://192.168.0.143:3306/mysql_lmj
    username: root
    password: root

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*