server:
  port: 8888

logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mtsql://IP地址:端口号/库名
    username:
    password:

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*